name: Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  BUILD_TYPE: core
  DEFAULT_PYTHON: 3.8

jobs:
  any_name:
    runs-on: ubuntu-latest
    steps:
      - name: Any Name Bash Test Step
        shell: bash
        run: |
          echo "NICK_LIFFEN: $NICK_LIFFEN"
          echo "NICK_LIFFEN: $NICK_LIFFEN"
          echo "NICK_LIFFEN: $NICK_LIFFEN"
        env:
          NICK_LIFFEN: ${{ env.NICK_LIFFEN }}
